import _ from "lodash";
import "./style.css";
import { inputBoxFunction } from "./createProject";
import { createTitle } from "./createPage";
import { loadOnPage } from "./loadOnPage";
import { showList } from "./accessTodoList";
import { deleteProject } from "./deleteProject";
import { checkForDark } from "./nightMode";
import { showSun } from "./nightMode";
import { showMenu } from "./nightMode";
import { getNewTodoData } from "./test";
checkForDark();
createTitle();
inputBoxFunction();
loadOnPage();
showList();
getNewTodoData();
